# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/zed.xdc

# IP: ip/axi_gpio_1/axi_gpio_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_1 || ORIG_REF_NAME==axi_gpio_1} -quiet] -quiet

# IP: ip/axi_gpio_0/axi_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_1/axi_gpio_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_1 || ORIG_REF_NAME==axi_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_1/axi_gpio_1_ooc.xdc

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_1/axi_gpio_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_1 || ORIG_REF_NAME==axi_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_0/axi_gpio_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/axi_gpio_0/axi_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: h:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
