@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 14 18:00:44 -0400 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim axi_ctrl_gpio_top_tb_behav -key {Behavioral:sim_1:Functional:axi_ctrl_gpio_top_tb} -tclbatch axi_ctrl_gpio_top_tb.tcl -view H:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.sim/sim_1/behav/top_led_wr_tb_behav.wcfg -log simulate.log"
call xsim  axi_ctrl_gpio_top_tb_behav -key {Behavioral:sim_1:Functional:axi_ctrl_gpio_top_tb} -tclbatch axi_ctrl_gpio_top_tb.tcl -view H:/workspace/AXI_IIC_Ctrl/axi_ctrl_gpio_zed/axi_ctrl_gpio_zed.sim/sim_1/behav/top_led_wr_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
